name: Random Cron
on:
  workflow_run:
    workflows: ["刷步数"]
    types:
      - completed

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11,需要repo和workflow权限
      - name: random cron
        run: |
          sed -i -E "s/(- cron: ')[0-9]+( [^[:space:]]+ \* \* \*')/\1$(($RANDOM % 50))\2/g" .github/workflows/run.yml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "random cron"
          git push origin master
  retry_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Retry main workflow
        uses: actions/github-script@v4
        with:
          script: |
            const octokit = github.getOctokit(core.getInput(secrets.PAT));
            await octokit.request('POST /repos/{context.repo.owner}/{context.repo.repo}/actions/runs/{context.payload.workflow_run.id}/rerun', {
              owner: context.repo.owner,
              repo: context.payload.workflow_run.id,
              run_id: context.payload.workflow_run.id,
            })
